[theme]
primaryColor = "#176961"
backgroundColor = "#F3F6F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172D32"
font = "sans serif"

[server]
headless = true
runOnSave = false
address = "0.0.0.0"
port = 8501

[client]
showSidebarNavigation = false
